#ifndef DATAPROCESS_GLOBAL_H
#define DATAPROCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAPROCESS_LIBRARY)
#  define DATAPROCESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAPROCESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAPROCESS_GLOBAL_H
