#ifndef DATAMANAGEMENT_GLOBAL_H
#define DATAMANAGEMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAMANAGEMENT_LIBRARY)
#  define DATAMANAGEMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAMANAGEMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAMANAGEMENT_GLOBAL_H
