#ifndef VOLUMERENDER_GLOBAL_H
#define VOLUMERENDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VOLUMERENDER_LIBRARY)
#  define VOLUMERENDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VOLUMERENDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VOLUMERENDER_GLOBAL_H
