#ifndef CEXCEPTION_H
#define CEXCEPTION_H

#include <string>
#include "UtilsGlobal.hpp"
#include "ExceptionCode.hpp"
#include "opencv2/opencv.hpp"

/**
 * @brief
 * This class is the base class for exceptions handling into the Ikomia environment.
 * All exceptions generated by the Ikomia API inherits from CException.
 * @ingroup groupUtils
 */
class UTILSSHARED_EXPORT CException : public std::exception
{
    public:

        //Constructors
        /**
         * @brief Default constructor
         */
        CException();             
        /**
         * @brief Constructor
         * @param code Exception code. See ExceptionCode.hpp for details.
         * @param error Exception message
         */
        CException(int code, const std::string &error);
        /**
         * @brief Constructor - The use of this constructor is recommended
         * @param code Exception code. See ExceptionCode.hpp for details.
         * @param error Exception message
         * @param func Function name from where the exception is thrown
         * @param file Source file from where the exception is thrown
         * @param line Line in source file from where the exception is thrown
         */
        CException(int code, const std::string& error, const std::string& func, const std::string& file, int line);
        /**
         * @brief Constructor from OpenCV cv::Exception
         * @param code Exception code. See ExceptionCode.hpp for details.
         * @param e OpenCV exception
         * @param func Function name from where the exception is thrown
         * @param file Source file from where the exception is thrown
         * @param line Line in source file from where the exception is thrown
         */
        CException(int code, const cv::Exception& e, const std::string &func, const std::string &file, int line);

        virtual ~CException();

        virtual const char* what() const noexcept override;

        //For Python binding
        std::string         getMessage() const;
        int                 getCode() const;
        std::string         getError() const;

    private:

        std::string         formatMessage() const;
        std::string         formatFile() const;

    private:

        int         m_code = CoreExCode::UNKNOWN;
        int         m_line = -1;
        int         m_msgType = 0;
        std::string m_error;
        std::string m_func;
        std::string m_file;
        std::string m_msg;
};

#endif // CEXCEPTION_H
